import Head from "next/head";
import styles from "../styles/Home.module.css";
import {useSelector, useDispatch} from "react-redux";
import {decrement, increment} from "../src/core/store/counter";
import {useStoreCounter} from "../src/core/store";

export default function Home() {
  const countState = useStoreCounter();
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{countState?.value}</div>
        <button onClick={() => dispatch(increment())}>increment</button>
        <button onClick={() => dispatch(decrement())}>decrement</button>
      </main>
    </div>
  );
}
